# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run test on staging environment"
    lane :stag do
    # add actions here: https://docs.fastlane.tools/actions
    sh("cd .. && mvn clean && mvn test -Denv.USER=stag")
    end

  desc "Run test on production environment"
    lane :prod do
      # add actions here: https://docs.fastlane.tools/actions
      sh("cd .. && mvn clean && mvn test -Denv.USER=prod")
    end
end
